language: cpp

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

script:
  - $CXX -std=c++11 -Wall -Wextra -pedantic -Wno-attributes -I. test/test.cpp
  
jobs:
  exclude:
  - os: windows
    compiler: clang
