os:
  - linux
  - osx
  - windows

dist: focal
  
language: cpp

compiler:
  - gcc
  - clang

install:
  - |-
      case $TRAVIS_OS_NAME in
        "windows")
          ./deps/install-deps-win32.bat
          ;;
        "linux")
          ./deps/install-deps-linux.sh
          ;;
        "osx")
          ./deps/install-deps-osx.sh
          ;;
      esac

cache:
  directories:
    - vcpkg/installed

script:
  - mkdir build
  - cd build
  - |-
      case $TRAVIS_OS_NAME in
        "windows")
          cmake -DCMAKE_TOOLCHAIN_FILE=..\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake ..
          ;;
        "linux"|"osx")
          cmake .. 
          ;;
      esac
  - make
  - make test

jobs:
  include:
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode12
    - os: windows
      dist: server-2016
